export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Test1RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <body>
        <header>
          header1
        </header>
        <main>
          {children}
        </main>
      </body>
    </>
  )
}
