
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';

import '@/app/globals.css';
import { ThemeProvider } from '@mui/material';

import theme from '@/app/theme';

import { Providers } from './redux/provider';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>
        <Providers>
          <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
              {children}
            </ThemeProvider>
          </AppRouterCacheProvider>
        </Providers>
      </body>
    </html>
  )
}
