
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';

import '@/app/globals.css';
import { ThemeProvider } from '@mui/material';
import theme from './theme';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            {children}
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
