

import Header from '@/app/components/common/header/Header';
import * as React from 'react';


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function MenuRootLayout({ children }: {
  children: React.ReactNode
}) {
  return (
    <>
      <Header />
      <main>
        {children}
      </main>
    </>
  )
}




